ecobit-blockchain-front-end/Ecobit-Blockchain-Frontend/Models/Batch.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Serialization;

namespace Ecobit_Blockchain_Frontend.Models
{
    public class Batch
    {
        [Required(ErrorMessage = "Partijnummer is verplicht")]
        [Display(Name = "Partijnummer")]
        [XmlElement("id")]
        public int BatchId { get; set; }

        [XmlElement("quantity")]
        public int Quantity { get; set; }

        [XmlElement("date_production")]
        public string ProductionDate { get; set; }

        [XmlElement("owner")]
        public string Owner { get; set; }
    }
}

ecobit-blockchain-front-end/Ecobit-Blockchain-Frontend/Models/UserHistory.cs
using System.Collections.Generic;

namespace Ecobit_Blockchain_Frontend.Models
{
    public class UserHistory
    {
        public string User { get; set; }
        public List<Transaction> Transactions { get; set; }
    }
}

ecobit-blockchain-front-end/Ecobit-Blockchain-Frontend/Models/View/HistoryView.cs
namespace Ecobit_Blockchain_Frontend.Models.View
{
    public class HistoryView
    {
        public SupplyChain SupplyChain { get; set; }
        public int BatchId { get; set; }
    }
}

ecobit-blockchain-front-end/Ecobit-Blockchain-Frontend/Controllers/BatchController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Ecobit_Blockchain_Frontend.Factories;
using Ecobit_Blockchain_Frontend.DataAccess.Interfaces;
using Ecobit_Blockchain_Frontend.Models;
using Ecobit_Blockchain_Frontend.Utils;
using Ecobit_Blockchain_Frontend.Utils.Auth;
using Ecobit_Blockchain_Frontend.Models.View;

namespace Ecobit_Blockchain_Frontend.Controllers
{
    [AuthenticationFilterAttribute]
    public class BatchController : Controller
    {
        private readonly ITransactionDao _transactionDao;
        private readonly IAuthenticationService _authService;

        public BatchController() : this(DependencyFactory.Resolve<ITransactionDao>(), DependencyFactory.Resolve<IAuthenticationService>())
        {
            
        }

        public BatchController(ITransactionDao transactionDao, IAuthenticationService authService)
        {
            _transactionDao = transactionDao;
            _authService = authService;
        }

        /// <summary>
        /// Returns index page with all controller function for transactions
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        
        /// <summary>
        /// Posts a Batch model to index and redirects it to the right page
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Index(Batch model)
        {
            return !ModelState.IsValid ? (ActionResult) View(model) : RedirectToAction("History", new
            {
                id = model.BatchId
            });
        }

        /// <summary>
        /// Returns a history of transactions for a batch id
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult History(int id)
        {
            var transactions = _transactionDao.GetTransactionsByBatchId(id);

            var supplyChain = SupplyChainFactory.Make(transactions);

            var model = new HistoryView
            {
                BatchId = id,
                SupplyChain = supplyChain
            };
            
            return View("History", model);
        }

        [HttpGet]
        public ActionResult UserHistory()
        {
            var cookie = HttpContext.Request.Cookies.Get(AuthenticationFilterAttribute.CookieName);
            return UserHistory(cookie);
        }
        
        
        /// <summary>
        /// Shows a page with transactions for the user
        /// </summary>
        /// <param name="cookie"></param>
        /// <returns></returns>
        public ActionResult UserHistory(HttpCookie cookie)
        {
            User userData = _authService.GetUserData(cookie);
            
            var transactions = _transactionDao.GetTransactionsByUser(userData.Companyname);
            transactions = transactions.OrderBy(t => t.OrderTime).ToList();

            var model = new UserHistory
            {
                User = userData.Companyname,
                Transactions = transactions
            };
            
            return View("UserHistory", model);
        }
        
        
        /// <summary>
        /// returns a batch creation page
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        
        /// <summary>
        /// Saves a transaction to the blockchain
        /// </summary>
        /// <param name="transaction"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(Transaction transaction)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("InvalidCreateTransaction", "Gegevens niet correct ingevuld.");
                return View(transaction);
            }
            
            _transactionDao.SaveTransaction(transaction);
            return View("Index");
        }
    }
}

ecobit-blockchain-front-end/Ecobit-Blockchain-Frontend/Views/Batch/Create.cshtml
@{
	ViewBag.Title = "Nieuwe Transactie";
}

@model Ecobit_Blockchain_Frontend.Models.Transaction
<div class="col-12">
	<h1>Nieuwe partij</h1>
</div>

@using (Html.BeginForm("Create", "Batch", FormMethod.Post))
{
	@Html.AntiForgeryToken()
		
	<div class="form-check-inline col-12">
		<div class="col-6">
			<label>@Html.LabelFor(m => Model.BatchId)</label>
			@Html.TextBoxFor(m => m.BatchId, new {@class = "form-control col-12"})
			<div class="has-error">
				<p>@Html.ValidationMessageFor(m => m.BatchId)</p>
			</div>
		</div>
		<div class="col-6">
			<label>@Html.LabelFor(m => m.Quantity)</label>
			@Html.TextBoxFor(m => m.Quantity, new {@class = "form-control col-12"})
			<div class="has-error">
				<p>@Html.ValidationMessageFor(m => m.Quantity)</p>
			</div>
		</div>
	</div>
	
	<div class="form-check-inline col-12">
		<div class="col-6">
			<label>@Html.LabelFor(m => m.ItemPrice)</label>
			@Html.TextBoxFor(m => m.ItemPrice, new {@class = "form-control col-12"})
			<div class="has-error">
				<p>@Html.ValidationMessageFor(m => m.ItemPrice)</p>
			</div>
		</div>
		<div class="col-6">
			<label>@Html.LabelFor(m => m.OrderTime)</label>
			@Html.TextBoxFor(m => m.OrderTime, new {@class = "form-control col-12", Type = "date"})
			<div class="has-error">
				<p>@Html.ValidationMessageFor(m => m.OrderTime)</p>
			</div>
		</div>
	</div>
	
	<div class="form-check-inline col-12">
		<div class="col-6">
			<label>@Html.LabelFor(m => m.FromOwner)</label>
			@Html.TextBoxFor(m => m.FromOwner, new {@class = "form-control col-12"})
			<div class="has-error">
				<p>@Html.ValidationMessageFor(m => m.FromOwner)</p>
			</div>
		</div>
		<div class="col-6">
			<label>@Html.LabelFor(m => m.ToOwner)</label>
			@Html.TextBoxFor(m => m.ToOwner, new {@class = "form-control col-12"})
			<div class="has-error">
				<p>@Html.ValidationMessageFor(m => m.ToOwner)</p>
			</div>
		</div>
	</div>

	<div class="form-check col-12">
		<div class="col-12">
			<div class="form-group has-error">
				<p>@Html.ValidationMessage("InvalidCreateTransaction")</p>
			</div>
			<button type="submit" class="btn btn-success">Voeg toe</button>
		</div>
	</div>
}

ecobit-blockchain-front-end/Ecobit-Blockchain-Frontend/Views/Batch/History.cshtml
@{
    ViewBag.Title = "Transactiehistorie";
}
@using Ecobit_Blockchain_Frontend.Models;
@using Ecobit_Blockchain_Frontend.Utils

@model Ecobit_Blockchain_Frontend.Models.View.HistoryView

<h1>Transactiehistorie</h1>
<h3>Partij @Model.BatchId</h3>

<div class="row">
    @if (Model.SupplyChain != null)
    {
        <div class="transaction first">
        @PrintSupplyChain(Model.SupplyChain, true)
        </div>
    }
    else
    {
        <div class="col-12 col-sm-12 col-md-3">
            <div class="alert alert-danger" role="alert">
                Geen transactiehistorie gevonden voor deze partij
            </div>
        </div>
    }
</div>

@helper PrintSupplyChain(SupplyChain chain, bool initial)
{

    <div class="complete-transaction childs-@chain.Children.Count">
        
        @if (!initial)
        {
            <div class="tree-branch"></div>
        }
        
        <div class="card bg-light" style="display: block;">
            <div class="card-body">
                <ul class="list-unstyled m-0">
                    <li><b>BatchId:</b> <span class="float-right">@chain.Transaction.BatchId</span></li>
                    <li><b>Hoeveelheid:</b> <span class="float-right">@chain.Transaction.Quantity</span></li>
                    <li><b>Prijs:</b> <span class="float-right">@chain.Transaction.ItemPrice</span></li>
                    <li><b>Datum:</b> <span class="float-right">@chain.Transaction.OrderTime</span></li>
                    <li><b>Van:</b> <span class="float-right">@chain.Transaction.FromOwner</span></li>
                    <li><b>Naar:</b> <span class="float-right">@chain.Transaction.ToOwner</span></li>
                </ul>

                @if (@chain.Transaction.Transport.PickupDate != DateTimeUtil.ConvertToDate(0))
                {
                    var t = @chain.Transaction.Transport;
                   
                    <div class="label-success mt-2">Transport voltooid</div>
                    <div class="card">
                        <div class="card-body py-2">
                            <ul class="list-unstyled m-0">
                                <li>Transporteur: <span class="float-right">@t.Transporter</span></li>
                                <li>Ophaaldatum: <span class="float-right">@(t.PickupDate != DateTimeUtil.ConvertToDate(0) ? t.PickupDate.ToString() : "(niet bekend)")</span></li>
                                <li>Afleverdatum: <span class="float-right">@(t.DeliverDate != DateTimeUtil.ConvertToDate(0) ? t.DeliverDate.ToString() : "(niet bekend)")</span></li>
                            </ul>
                        </div>
                    </div>
                }
                else
                {
                    <div class="label-warning mt-2">In transport</div>
                }
            </div>
        </div>

        <div class="transaction">
            @foreach (var child in chain.Children)
            {
                @PrintSupplyChain(child, false)
            }
        </div>
    </div>
}

ecobit-blockchain-front-end/Ecobit-Blockchain-Frontend/Views/Batch/Index.cshtml
@{
    ViewBag.Title = "Transactie";
}

@model Ecobit_Blockchain_Frontend.Models.Batch
<div class="col-2">
    <a href="@Url.Action("Create", "Batch")">
        <button class="btn btn-success btn-block">
            <i class="fa fa-fw fa-plus-square"></i>
            Partij toevoegen
        </button>
    </a>
</div>
<div class="form-page" style="margin-top: 10%">
    <div class="row">
        @using (Html.BeginForm("Index", "Batch", FormMethod.Post, new {style = "width: 100%;", @class = "Batch"}))
        {
            <div class="form-group" style="text-align: center;">
                <label>
                    @Html.LabelFor(m => m.BatchId)
                </label>
                @Html.TextBoxFor(m => m.BatchId, new {style = "width: 100%; margin-left:30%; margin-right: 30%; max-width:40%;", @class = "form-control"})
                <div class="has-error">
                    <p>@Html.ValidationMessageFor(m => m.BatchId)</p>
                </div>
            </div>
            <div style="width: 100%; margin-left: 35%">
                <button type="submit" class="btn btn-primary" style="width: 15%">Toon transactiehistorie</button>
                <a class="btn btn-primary" href="@Url.Action("UserHistory", "Batch")" style="width: 15%">Toon mijn transacties</a>
            </div>
        }
    </div>
</div>

ecobit-blockchain-front-end/Ecobit-Blockchain-Frontend/Views/Batch/UserHistory.cshtml
@{
    ViewBag.Title = "Gebruikers Transactiehistorie";
}
@model Ecobit_Blockchain_Frontend.Models.UserHistory

<h1>Gebruikers Transactiehistorie</h1>
<h3>Gebruiker: @Model.User</h3>

<div class="row">
    @if (Model.Transactions.Count > 0)
    {
         foreach (var transaction in Model.Transactions)
         {
             <div class="col-sm-12 col-md-4">
                 <div class="card bg-light mb-3">
                     <div class="card-body">
                         <ul class="list-unstyled m-0">
                             <li>BatchId: <span class="float-right">@transaction.BatchId</span></li>
                             <li>Hoeveelheid: <span class="float-right">@transaction.Quantity</span></li>
                             <li>Prijs: <span class="float-right">@transaction.ItemPrice</span></li>
                             <li>Datum: <span class="float-right">@transaction.OrderTime</span></li>
                             <li>Van: <span class="float-right">@transaction.FromOwner</span></li>
                             <li>Naar: <span class="float-right">@transaction.ToOwner</span></li>
                         </ul>
    
                         @if (transaction.Transport != null)
                         {
                             var t = transaction.Transport;
                             <label class="mt-3">Transport gegevens:</label>
                             <div class="card">
                                 <div class="card-body py-2">
                                     <ul class="list-unstyled m-0">
                                     <li>Transporteur: <span class="float-right">@t.Transporter</span></li>
                                     <li>Ophaaldatum: <span class="float-right">@(t.PickupDate != DateTime.MinValue ? t.PickupDate.ToString() : "(niet bekend)")</span></li>
                                     <li>Afleverdatum: <span class="float-right">@(t.DeliverDate != DateTime.MinValue ? t.DeliverDate.ToString() : "(niet bekend)")</span></li>
                                     </ul>
                                 </div>
                             </div>
                         }
                     </div>
                 </div>
             </div>
        }
    }
    else
    {
        <div class="col-12 col-sm-12 col-md-3">
            <div class="alert alert-danger" role="alert">
                Geen transactiehistorie gevonden voor deze partij
            </div>
        </div>
    }
</div>